In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv("dirty.csv")

In [3]:
df

,appointment_id,patient_id,age,gender,city,neighborhood,scheduled_day,appointment_day,waiting_days,appointment_hour,...,temperature_celsius,rainy_day,employment_status,education_level,income_level,marital_status,children_count,patient_satisfaction_score,no_show_probability,no_show
0,APT-100000,PAT-25795,42,Female,Almere,East,2024-07-10,2024-07-14,4,8,...,15.3,0,Employed,Secondary,Middle,Single,0,6.9,0.0319,0
1,APT-100001,PAT-10860,9,Male,Groningen,West,2024-01-21,2024-02-07,17,12,...,13.9,0,Retired,Secondary,Middle,Married,1,4.7,0.0559,0
2,APT-100002,PAT-86820,27,Female,Utrecht,East,2025-09-06,2025-09-08,2,14,...,3.5,0,Employed,Secondary,Middle,Single,2,9.5,0.0201,0
3,APT-100003,PAT-64886,0,Female,The Hague,Rural,2024-01-24,2024-02-04,11,10,...,18.5,0,Unemployed,Secondary,Lower-Middle,Divorced,0,5.8,0.0627,1
4,APT-100004,PAT-16265,39,Male,Almere,Suburban,2025-03-27,2025-04-13,17,10,...,1.8,0,Student,NaN,NaN,Divorced,0,NaN,0.0792,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,APT-149995,PAT-77722,18,Male,Rotterdam,East,2025-11-26,2025-12-10,14,13,...,21.0,0,Student,Vocational,Middle,Single,0,10.0,0.0331,0
49996,APT-149996,PAT-54279,10,Male,Eindhoven,North,2024-02-05,2024-02-19,14,8,...,8.7,0,Employed,Vocational,Upper-Middle,Married,2,7.8,0.0390,1
49997,APT-149997,PAT-19398,27,Male,Amsterdam,Suburban,2025-05-18,2025-06-18,31,14,...,12.8,0,Employed,Vocational,Middle,Single,2,3.5,0.1165,0
49998,APT-149998,PAT-71140,41,Male,Utrecht,North,2024-06-04,2024-07-25,51,12,...,33.0,1,Unemployed,Vocational,Middle,Married,0,7.5,0.2014,0
49999,APT-149999,PAT-14518,43,Male,Groningen,West,2024-04-17,2024-04-23,6,9,...,6.4,1,Self-employed,Secondary,Upper-Middle,Married,1,8.4,0.1308,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 39 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   appointment_id              50000 non-null  object
 1   patient_id                  50000 non-null  object
 2   age                         50000 non-null  int64
 3   gender                      50000 non-null  object
 4   city                        50000 non-null  object
 5   neighborhood                50000 non-null  object
 6   scheduled_day               50000 non-null  object
 7   appointment_day             50000 non-null  object
 8   waiting_days                50000 non-null  int64
 9   appointment_hour            50000 non-null  int64
 10  day_of_week                 50000 non-null  object
 11  month                       50000 non-null  int64
 12  sms_received                50000 non-null  int64
 13  reminder_calls              50000 non-null  int64
 14  previous_appointments       50000 non-null  int64
 15  previous_no_shows           50000 non-null  int64
 16  no_show_rate                50000 non-null  float64
 17  distance_km                 50000 non-null  float64
 18  transportation_type         48750 non-null  object
 19  insurance_type              49250 non-null  object
 20  has_chronic_disease         50000 non-null  int64
 21  hypertension                50000 non-null  int64
 22  diabetes                    50000 non-null  int64
 23  alcoholism                  50000 non-null  int64
 24  disability                  50000 non-null  int64
 25  appointment_type            50000 non-null  object
 26  doctor_specialty            50000 non-null  object
 27  clinic_type                 50000 non-null  object
 28  weather_condition           50000 non-null  object
 29  temperature_celsius         50000 non-null  float64
 30  rainy_day                   50000 non-null  int64
 31  employment_status           50000 non-null  object
 32  education_level             48500 non-null  object
 33  income_level                48000 non-null  object
 34  marital_status              50000 non-null  object
 35  children_count              50000 non-null  int64
 36  patient_satisfaction_score  49000 non-null  float64
 37  no_show_probability         50000 non-null  float64
 38  no_show                     50000 non-null  int64
dtypes: float64(5), int64(16), object(18)
memory usage: 14.9+ MB

### All the columns will not be necessary. We are removing too weak columns for our analysis.

In [5]:
df = df.drop(columns = ["appointment_id","city","day_of_week","insurance_type","education_level"])

In [6]:
df

,patient_id,age,gender,neighborhood,scheduled_day,appointment_day,waiting_days,appointment_hour,month,sms_received,...,weather_condition,temperature_celsius,rainy_day,employment_status,income_level,marital_status,children_count,patient_satisfaction_score,no_show_probability,no_show
0,PAT-25795,42,Female,East,2024-07-10,2024-07-14,4,8,7,1,...,Sunny,15.3,0,Employed,Middle,Single,0,6.9,0.0319,0
1,PAT-10860,9,Male,West,2024-01-21,2024-02-07,17,12,2,0,...,Cloudy,13.9,0,Retired,Middle,Married,1,4.7,0.0559,0
2,PAT-86820,27,Female,East,2025-09-06,2025-09-08,2,14,9,1,...,Sunny,3.5,0,Employed,Middle,Single,2,9.5,0.0201,0
3,PAT-64886,0,Female,Rural,2024-01-24,2024-02-04,11,10,2,1,...,Sunny,18.5,0,Unemployed,Lower-Middle,Divorced,0,5.8,0.0627,1
4,PAT-16265,39,Male,Suburban,2025-03-27,2025-04-13,17,10,4,0,...,Sunny,1.8,0,Student,NaN,Divorced,0,NaN,0.0792,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,PAT-77722,18,Male,East,2025-11-26,2025-12-10,14,13,12,1,...,Sunny,21.0,0,Student,Middle,Single,0,10.0,0.0331,0
49996,PAT-54279,10,Male,North,2024-02-05,2024-02-19,14,8,2,0,...,Sunny,8.7,0,Employed,Upper-Middle,Married,2,7.8,0.0390,1
49997,PAT-19398,27,Male,Suburban,2025-05-18,2025-06-18,31,14,6,1,...,Sunny,12.8,0,Employed,Middle,Single,2,3.5,0.1165,0
49998,PAT-71140,41,Male,North,2024-06-04,2024-07-25,51,12,7,1,...,Rainy,33.0,1,Unemployed,Middle,Married,0,7.5,0.2014,0
49999,PAT-14518,43,Male,West,2024-04-17,2024-04-23,6,9,4,0,...,Rainy,6.4,1,Self-employed,Upper-Middle,Married,1,8.4,0.1308,0

In [7]:
# 1. Converting categorical text to Category type
cat_cols = [
    'patient_id', 'gender', 'neighborhood', 'transportation_type', 
    'appointment_type', 'doctor_specialty', 'clinic_type', 
    'weather_condition', 'employment_status', 'income_level', 'marital_status'
]
df[cat_cols] = df[cat_cols].astype('category')

# 2. Converting date strings to Datetime type
df['scheduled_day'] = pd.to_datetime(df['scheduled_day'])
df['appointment_day'] = pd.to_datetime(df['appointment_day'])

# 3. Optimizing integers (downcast sizes to save memory)
int_cols = [
    'sms_received', 'has_chronic_disease', 'hypertension', 
    'diabetes', 'alcoholism', 'disability', 'rainy_day', 'no_show', 'age', 'waiting_days', 'appointment_hour', 'month', 
    'previous_appointments', 'previous_no_shows', 'children_count', 'reminder_calls'
]
for col in int_cols:
    df[col] = pd.to_numeric(df[col], downcast='integer')

# 4. Optimizing floats (downcast sizes to save memory)
float_cols = ['no_show_rate', 'distance_km', 'temperature_celsius', 'no_show_probability']
for col in float_cols:
    df[col] = pd.to_numeric(df[col], downcast='float')

# Using nullable Float64 for satisfaction score due to missing data (NaN)
df['patient_satisfaction_score'] = df['patient_satisfaction_score'].astype('Float64')

In [8]:
df.isnull().sum()

patient_id                       0
age                              0
gender                           0
neighborhood                     0
scheduled_day                    0
appointment_day                  0
waiting_days                     0
appointment_hour                 0
month                            0
sms_received                     0
reminder_calls                   0
previous_appointments            0
previous_no_shows                0
no_show_rate                     0
distance_km                      0
transportation_type           1250
has_chronic_disease              0
hypertension                     0
diabetes                         0
alcoholism                       0
disability                       0
appointment_type                 0
doctor_specialty                 0
clinic_type                      0
weather_condition                0
temperature_celsius              0
rainy_day                        0
employment_status                0
income_level                  2000
marital_status                   0
children_count                   0
patient_satisfaction_score    1000
no_show_probability              0
no_show                          0
dtype: int64

Look, 2000 data missing in the column "income_level". we will drop the rows with these missing data.

In [9]:
df = df.dropna(subset = "income_level")

In [10]:
df.isnull().sum()

patient_id                    0
age                           0
gender                        0
neighborhood                  0
scheduled_day                 0
appointment_day               0
waiting_days                  0
appointment_hour              0
month                         0
sms_received                  0
reminder_calls                0
previous_appointments         0
previous_no_shows             0
no_show_rate                  0
distance_km                   0
transportation_type           0
has_chronic_disease           0
hypertension                  0
diabetes                      0
alcoholism                    0
disability                    0
appointment_type              0
doctor_specialty              0
clinic_type                   0
weather_condition             0
temperature_celsius           0
rainy_day                     0
employment_status             0
income_level                  0
marital_status                0
children_count                0
patient_satisfaction_score    0
no_show_probability           0
no_show                       0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
(df["age"] < 0).sum()

np.int64(0)

In [13]:
(df['age'] >100).sum()

np.int64(0)

In [25]:
df['gender'] = df['gender'].str.lower()

C:\Users\hp\AppData\Local\Temp\ipykernel_11456\3065845865.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gender'] = df['gender'].str.lower()

In [15]:
df['gender'] = df['gender'].map({"male":1,"female":0})

C:\Users\hp\AppData\Local\Temp\ipykernel_11456\389552021.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gender'] = df['gender'].map({"male":1,"female":0})

In [16]:
df['gender']

0        0.0
1        1.0
2        0.0
3        0.0
5        1.0
        ...
49995    1.0
49996    1.0
49997    1.0
49998    1.0
49999    1.0
Name: gender, Length: 48000, dtype: float64

In [17]:
string_cols = df.select_dtypes(include=['object', 'string']).columns
for col in string_cols:
    df[col] = df[col].astype(str).str.lower()

In [18]:
df

,patient_id,age,gender,neighborhood,scheduled_day,appointment_day,waiting_days,appointment_hour,month,sms_received,...,weather_condition,temperature_celsius,rainy_day,employment_status,income_level,marital_status,children_count,patient_satisfaction_score,no_show_probability,no_show
0,PAT-25795,42,0.0,East,2024-07-10,2024-07-14,4,8,7,1,...,Sunny,15.300000,0,Employed,Middle,Single,0,6.9,0.0319,0
1,PAT-10860,9,1.0,West,2024-01-21,2024-02-07,17,12,2,0,...,Cloudy,13.900000,0,Retired,Middle,Married,1,4.7,0.0559,0
2,PAT-86820,27,0.0,East,2025-09-06,2025-09-08,2,14,9,1,...,Sunny,3.500000,0,Employed,Middle,Single,2,9.5,0.0201,0
3,PAT-64886,0,0.0,Rural,2024-01-24,2024-02-04,11,10,2,1,...,Sunny,18.500000,0,Unemployed,Lower-Middle,Divorced,0,5.8,0.0627,1
5,PAT-92386,37,1.0,North,2024-04-25,2024-05-04,9,16,5,1,...,Sunny,19.700001,0,Unemployed,Lower-Middle,Married,0,6.6,0.0185,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,PAT-77722,18,1.0,East,2025-11-26,2025-12-10,14,13,12,1,...,Sunny,21.000000,0,Student,Middle,Single,0,10.0,0.0331,0
49996,PAT-54279,10,1.0,North,2024-02-05,2024-02-19,14,8,2,0,...,Sunny,8.700000,0,Employed,Upper-Middle,Married,2,7.8,0.0390,1
49997,PAT-19398,27,1.0,Suburban,2025-05-18,2025-06-18,31,14,6,1,...,Sunny,12.800000,0,Employed,Middle,Single,2,3.5,0.1165,0
49998,PAT-71140,41,1.0,North,2024-06-04,2024-07-25,51,12,7,1,...,Rainy,33.000000,1,Unemployed,Middle,Married,0,7.5,0.2014,0
49999,PAT-14518,43,1.0,West,2024-04-17,2024-04-23,6,9,4,0,...,Rainy,6.400000,1,Self-employed,Upper-Middle,Married,1,8.4,0.1308,0

In [19]:
df.dtypes

patient_id                          category
age                                     int8
gender                               float64
neighborhood                        category
scheduled_day                 datetime64[ns]
appointment_day               datetime64[ns]
waiting_days                            int8
appointment_hour                        int8
month                                   int8
sms_received                            int8
reminder_calls                          int8
previous_appointments                   int8
previous_no_shows                       int8
no_show_rate                         float32
distance_km                          float32
transportation_type                 category
has_chronic_disease                     int8
hypertension                            int8
diabetes                                int8
alcoholism                              int8
disability                              int8
appointment_type                    category
doctor_specialty                    category
clinic_type                         category
weather_condition                   category
temperature_celsius                  float32
rainy_day                               int8
employment_status                   category
income_level                        category
marital_status                      category
children_count                          int8
patient_satisfaction_score           Float64
no_show_probability                  float32
no_show                                 int8
dtype: object

In [20]:
df.to_csv("cleaned_data.csv")

## complete!